#!/usr/bin/env python3
"""Export SQLite tables as Supabase dashboard CSV imports plus schema SQL."""

from __future__ import annotations

import csv
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "backend" / "sentinel.db"
OUTPUT = ROOT / "backend" / "generated" / "cloud-import"
TABLES = ("sources", "articles", "synopses", "briefs", "audio_briefs", "system_status")
BOOLEAN_COLUMNS = {
    "sources": {"enabled"},
    "articles": {"is_sigact", "processed", "is_cluster_primary", "alerted"},
}

SCHEMA_SQL = """BEGIN;
CREATE TABLE sources (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR NOT NULL,
 kind VARCHAR NOT NULL, url_or_handle VARCHAR NOT NULL UNIQUE, ao VARCHAR NOT NULL,
 reliability VARCHAR, enabled BOOLEAN, last_fetched_at TIMESTAMP, last_error VARCHAR, error_count INTEGER
);
CREATE TABLE articles (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_id INTEGER,
 title VARCHAR NOT NULL, url VARCHAR NOT NULL, summary TEXT, published_at TIMESTAMP NOT NULL,
 fetched_at TIMESTAMP, ao VARCHAR, category VARCHAR, country VARCHAR, lat DOUBLE PRECISION,
 lon DOUBLE PRECISION, severity INTEGER, is_sigact BOOLEAN, processed BOOLEAN,
 classifier_version INTEGER, cluster_key VARCHAR, is_cluster_primary BOOLEAN, alerted BOOLEAN
);
CREATE TABLE synopses (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ao VARCHAR NOT NULL, "window" VARCHAR NOT NULL,
 strategic TEXT, operational TEXT, tactical TEXT, generated_at TIMESTAMP, source_article_count INTEGER
);
CREATE TABLE briefs (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ao VARCHAR NOT NULL,
 generated_at TIMESTAMP, content TEXT NOT NULL, fact_check_notes TEXT, source_article_count INTEGER
);
CREATE TABLE audio_briefs (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, episode_date VARCHAR NOT NULL UNIQUE,
 generated_at TIMESTAMP, period_start TIMESTAMP NOT NULL, period_end TIMESTAMP NOT NULL,
 title VARCHAR NOT NULL, transcript TEXT NOT NULL, chapters_json TEXT NOT NULL,
 audio_filename VARCHAR, mime_type VARCHAR NOT NULL, duration_seconds DOUBLE PRECISION,
 word_count INTEGER, source_article_count INTEGER, voice_engine VARCHAR, status VARCHAR NOT NULL,
 last_error TEXT
);
CREATE TABLE system_status (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, component VARCHAR NOT NULL UNIQUE,
 last_success_at TIMESTAMP, last_attempt_at TIMESTAMP, last_error VARCHAR
);
CREATE INDEX ix_articles_published_at ON articles(published_at);
CREATE INDEX ix_articles_ao ON articles(ao);
CREATE INDEX ix_articles_cluster_key ON articles(cluster_key);
CREATE UNIQUE INDEX ux_articles_url_hash ON articles(md5(url));
CREATE INDEX ix_briefs_ao ON briefs(ao);
CREATE INDEX ix_audio_briefs_episode_date ON audio_briefs(episode_date);
CREATE INDEX ix_audio_briefs_generated_at ON audio_briefs(generated_at);
COMMIT;
"""

FINALISE_SQL = """BEGIN;
SELECT setval(pg_get_serial_sequence('sources','id'), COALESCE(MAX(id),1), true) FROM sources;
SELECT setval(pg_get_serial_sequence('articles','id'), COALESCE(MAX(id),1), true) FROM articles;
SELECT setval(pg_get_serial_sequence('synopses','id'), COALESCE(MAX(id),1), true) FROM synopses;
SELECT setval(pg_get_serial_sequence('briefs','id'), COALESCE(MAX(id),1), true) FROM briefs;
SELECT setval(pg_get_serial_sequence('audio_briefs','id'), COALESCE(MAX(id),1), true) FROM audio_briefs;
SELECT setval(pg_get_serial_sequence('system_status','id'), COALESCE(MAX(id),1), true) FROM system_status;
COMMIT;
"""


def main() -> int:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "00-schema.sql").write_text(SCHEMA_SQL, encoding="utf-8")
    (OUTPUT / "99-finalise.sql").write_text(FINALISE_SQL, encoding="utf-8")
    db = sqlite3.connect(SOURCE)
    db.row_factory = sqlite3.Row
    for position, table in enumerate(TABLES, start=1):
        rows = db.execute(f'SELECT * FROM "{table}" ORDER BY id').fetchall()
        columns = [item[1] for item in db.execute(f'PRAGMA table_info("{table}")')]
        path = OUTPUT / f"{position:02d}-{table}.csv"
        with path.open("w", encoding="utf-8", newline="") as target:
            writer = csv.DictWriter(target, fieldnames=columns)
            writer.writeheader()
            for row in rows:
                values = dict(row)
                for column in BOOLEAN_COLUMNS.get(table, set()):
                    if values[column] is not None:
                        values[column] = "true" if values[column] else "false"
                writer.writerow(values)
        print(f"{table}: {len(rows)} rows -> {path.name}")
        if table == "articles":
            for chunk_index, start in enumerate(range(0, len(rows), 2000), start=1):
                chunk_path = OUTPUT / f"02-articles-{chunk_index:02d}.csv"
                with chunk_path.open("w", encoding="utf-8", newline="") as target:
                    writer = csv.DictWriter(target, fieldnames=columns)
                    writer.writeheader()
                    for row in rows[start:start + 2000]:
                        values = dict(row)
                        for column in BOOLEAN_COLUMNS[table]:
                            if values[column] is not None:
                                values[column] = "true" if values[column] else "false"
                        writer.writerow(values)
    db.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
